### ISSUE TITLE
Add a default operator

### ISSUE THREAD

**Issue by mariovalney** [eduardoboucas/include-media#174]
Hi! 
First of all: thank you for this excellent tool.

I would like to suggest add a default operator (<) so we can use:

`@include media('mobile') {`

What do you think?

**Comment by Toddses** [comment]
As a regular user of this library, I'm not a fan of this suggestion. If you're doing mobile first CSS, using `<` as a default operator is not ideal.

And as a person who regularly reviews code, I'm not a fan because it's not explicit as to what the media query will be doing. It takes little to no effort to type `<` or `>=` so personally, I don't see the benefit here.

That said, if this was implemented I'd still use the library, our code standards would just not allow this usage.

**Comment by HugoGiraudel** [comment]
Hello! I am not convinced this is a good idea. A default is only good when it’s obvious. Some people might expect `<` to be the default, and some people might expect `>` to be the default. Also, why `<` and not `≤`? It’s a little too opinionated to be a default.

**Comment by mariovalney** [comment]
As you closed it, I guess you are not interested to discuss, but I suggested < because mobile first.

Anyway, thank you again for your tool.

**Comment by HugoGiraudel** [comment]
Hey Mario! I didn’t mean to be rude by closing it, I just don’t think that’s an addition that will better the library without downsides. Happy to have @eduardoboucas’ opinion. If he thinks it’s a good idea, we should reopen this issue (and the associated PR). :)

**Comment by eduardoboucas** [comment]
I agree with @HugoGiraudel. The syntax for using a breakpoint is already very short and declarative. Creating a default value will mean that some people will have to write one less character, but other people might be confused and get unexpected results without realising what's going on.

Thanks for your suggestion though!
